eureka:
  client:
  service-url:
      defaultZone: http://localhost:8762/eureka/
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.49:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
server:
  port: 8081

env:
    test222