spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.49:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
jpa:
  show-sql: true
